### ISSUE TITLE
Issue: Exec Failure: com.github.dockerjava.api.exception.NotFoundException: No such image: alpine/socat:latest

### ISSUE THREAD

**Issue by cmoulliard** [kameshsampath/kind-nodeport-controller#6]
## Issue

```
java -Ddev.kameshs.watcher.kind-name=demos -jar target/kind-nodeport-controller-runner.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-27 18:36:25,712 INFO  [io.quarkus] (main) kind-nodeport-controller 0.1.0-SNAPSHOT (powered by Quarkus 1.4.2.Final) started in 3.018s. Listening on: http://0.0.0.0:8080
2020-05-27 18:36:25,739 INFO  [io.quarkus] (main) Profile prod activated.
2020-05-27 18:36:25,739 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, kubernetes-client, mutiny, narayana-jta, resteasy, smallrye-health, smallrye-openapi, vertx]
2020-05-27 18:36:32,190 INFO  [dev.kam.ServiceWatcherResource] (executor-thread-1) Expose NS demos
2020-05-27 18:36:32,200 INFO  [dev.kam.ser.WatchNamespaceService] (vert.x-eventloop-thread-14) Got to watch service in namespace demos
2020-05-27 18:36:32,681 INFO  [dev.kam.wat.ServiceWatcher] (OkHttp https://127.0.0.1:54156/...) Service Event ADDED Received for myapp
2020-05-27 18:36:32,997 INFO  [dev.kam.wat.ServiceWatcher] (OkHttp https://127.0.0.1:54156/...) Run new container
2020-05-27 18:36:33,190 INFO  [dev.kam.uti.ContainerUtility] (OkHttp https://127.0.0.1:54156/...) Starting Container
2020-05-27 18:36:33,843 WARN  [io.fab.kub.cli.dsl.int.WatchConnectionManager] (OkHttp https://127.0.0.1:54156/...) Exec Failure: com.github.dockerjava.api.exception.NotFoundException: No such image: alpine/socat:latest
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:66)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:171)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:159)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:301)
```

**Comment by kameshsampath** [comment]
Have you set your registry to something that’s not docker.io?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cmoulliard** [comment]
I pulled manually the image and the problem is gone 

```
docker images
...
alpine/socat                       latest              2398cf75de68        4 months ago        9.06MB
```

**Comment by kameshsampath** [comment]
That’s weird :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cmoulliard** [comment]
FYI, the following scenario is working on my macbook using docker client

```
# Create a kind cluster and expose extra port for docker -> 31500
kind delete cluster --name demo
cat <<EOF | kind create cluster --name demo --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31500
    hostPort: 31500
    protocol: TCP
    listenAddress: "127.0.0.1"
EOF

# Deploy the demo application
kc create ns demo
cat <<EOF | kc apply -n demo -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: quay.io/kameshsampath/quarked:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
EOF
kc expose deployment myapp -n demo --port=8080 --target-port=8080 --type=NodePort
kc patch service myapp -n demo --type='json' --patch='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value":31500}]'

# Access the quarkus application
http :31500
```

**Comment by kameshsampath** [comment]
My point is to have multiple node ports for which setting at cluster level might not help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
